name: Java-SDK GitHub Actions
on:
  push:
  pull_request:
env:
  CCACHE_DIR: ${{ github.workspace }}/ccache

jobs:
  build:
    name: build
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-18.04, ubuntu-20.04, macos-latest]
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 5
      - name: install macOS dependencies
        if: runner.os == 'macOS'
        run: brew install openssl@1.1 openjdk
      - name: install Ubuntu dependencies
        if: runner.os == 'Linux'
        run: sudo apt-get update && sudo apt install -y git default-jdk
      - name: run integration testing
        run: /bin/bash .ci/ci_check.sh